version: '3.5'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./conf.d:/etc/nginx/conf.d
    - ./vhost.d:/etc/nginx/vhost.d
    - ./html:/usr/share/nginx/html
    - ./certs:/etc/nginx/certs:ro
    - ./htpasswd:/etc/nginx/htpasswd:ro
    network_mode: bridge

  config:
    image: jwilder/docker-gen
    restart: unless-stopped
    container_name: nginx-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
    - ./conf.d:/etc/nginx/conf.d
    - ./vhost.d:/etc/nginx/vhost.d
    - ./html:/usr/share/nginx/html
    - ./certs:/etc/nginx/certs:ro
    - ./htpasswd:/etc/nginx/htpasswd:ro
    - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    environment:
    - NGINX_PROXY_CONTAINER=nginx
    - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    volumes:
    - ./conf.d:/etc/nginx/conf.d
    - ./vhost.d:/etc/nginx/vhost.d
    - ./html:/usr/share/nginx/html
    - ./certs:/etc/nginx/certs:rw
    - ./htpasswd:/etc/nginx/htpasswd:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
