---

- name: Get nginx userid
  shell: docker exec nginx-proxy id -u nginx
  register: nginx_uid

- name: Create directories
  file:
    path: '{{ nginx_home }}{{ item }}'
    state: directory
    owner: '{{ nginx_uid.stdout }}'
    mode: 0700
  with_items:
  - vhosts.d
  - htpasswd

- name: Install htaccess
  when: password|default(false)
  htpasswd:
    path: '{{ nginx_home }}/htpasswd/{{ domain }}'
    name: '{{ item.name }}'
    password: '{{ password }}'
    owner: '{{ nginx_uid.stdout }}'
    mode: 0600

# not that fast: wait for actual use case to enable
# - name: Get custom nginx configuration from the image if any
#   shell: '{{ exec }} bash -c "test ! -f /app/etc/nginx.conf || cat /app/etc/nginx.conf"'
#   register: nginx_config

- name: Configure nginx
  copy:
    dest: '{{ nginx_home }}vhosts.d/{{ domain }}'
    content: |
      client_max_body_size 10M;
      client_body_buffer_size 10M;
      uwsgi_buffering off;

- name: Configure nginx for redirects
  with_items: '{{ redirects|default([]) }}'
  copy:
    dest: '{{ nginx_home }}vhosts.d/{{ item }}_location'
    content: rewrite ^/(.*) https://{{ dns }}/$1 permanent;
