---

- include_role: name=yourlabs.remember
- include_role: name=yourlabs.remember tasks_from=require_once
  vars: {rolename: yourlabs.docker}

- name: Set nginx_env
  when: acme != 'httponly'
  set_fact:
    nginx_env:
      ACME_CA_URI: '{{ acme }}'

- name: Set Log driver
  set_fact:
    log_driver: "{{ 'syslog' if ansible_os_family == 'Alpine' else 'journald' }}"

- name: Install passlib library for ansible htpasswd module
  pip:
    name: passlib
    state: present

- name: Create nginx-proxy container with jwilder/nginx-proxy
  docker_container:
    pull: true
    name: nginx-proxy
    image: '{{ image }}'
    hostname: nginx-proxy
    published_ports: ['80:80', '443:443']
    restart_policy: always
    log_driver: '{{ log_driver }}'
    volumes:
    - '{{ home }}conf.d:/etc/nginx/conf.d'
    - '{{ home }}vhosts.d:/etc/nginx/vhost.d'
    - '{{ home }}certs:/etc/nginx/certs:ro'
    - '{{ home }}html:/usr/share/nginx/html:rw'
    - '{{ home }}htpasswd:/etc/nginx/htpasswd:ro'
    - /var/run/docker.sock:/tmp/docker.sock:ro
    labels: com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=nginx-letsencrypt

- name: Create nginx-letsencrypt container with jrcs/letsencrypt-nginx-proxy-companion
  when: letsencrypt_email|default()
  docker_container:
    pull: true
    name: nginx-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from: [nginx-proxy]
    restart_policy: always
    log_driver: '{{ log_driver }}'
    env: '{{ nginx_env|default({}) }}'
    volumes:
    - '{{ home }}certs:/etc/nginx/certs:rw'
    - /var/run/docker.sock:/var/run/docker.sock:ro
