---

- include_role: name=yourlabs.remember
- include_role: name=yourlabs.remember tasks_from=require_once
  vars: {rolename: yourlabs.docker}

- name: Set nginx_env
  when: acme|bool
  set_fact:
    nginx_env:
      ACME_CA_URI: '{{ acme }}'

- name: Set Log driver
  set_fact:
    log_driver: "{{ 'syslog' if ansible_os_family == 'Alpine' else 'journald' }}"

- name: Install passlib library for ansible htpasswd module
  pip:
    name: passlib
    state: present

- name: Upload {{ home }}/{{ item }}
  copy:
    src: '{{ role_path }}/{{ item }}'
    dest: '{{ home }}/{{ item }}'
  with_items:
  - docker-compose.yml
  - nginx.tmpl

- name: Start {{ home }}/docker-compose.yml
  docker_compose:
    project_src: '{{ home }}'
    restarted: yes
    pull: yes
    recreate: always

- include_role: name=yourlabs.remember tasks_from=success
