---

- name: Ensure docker was setup once on this host
  include_role: name=yourlabs.compose
  vars:
    compose: ./docker-compose.yml
    home: /etc/nginx

# not that fast: wait for actual use case to enable
# - name: Get custom nginx configuration from the image if any
#   shell: '{{ exec }} bash -c "test ! -f /app/etc/nginx.conf || cat /app/etc/nginx.conf"'
#   register: nginx_config
